#Dockerfile.redis
FROM redis:4.0.9

RUN mkdir  /var/log/redis
RUN mkdir  /usr/local/etc/redis
RUN mkdir /var/lib/redis

EXPOSE 6379

COPY ./conf/redis/redis.conf /usr/local/etc/redis/redis.conf

COPY ./docker-redis-entrypoint.sh /docker-redis-entrypoint.sh

CMD redis-server /usr/local/etc/redis/redis.conf






